
name: Tweet latest progress
 
on:
  schedule:
    - cron:  '0 10 * * *'  # 10:00 UTC (vaccination data is typically updated in the morning in UK time)

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9.1'
      - name: run script
        env:
          BOT_API: ${{ secrets.BOT_CHAT_ID }}
          BOT_API_SECRET: ${{ secrets.BOT_TOKEN }}
        run: python zvibot.py
